name: Generate project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Generated project')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Make script executable
        run: chmod +x ./create_repo_script.sh
      - name: Run script
        run: bash ./create_repo_script.sh
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Generated project"
          git push
